"""
Auto-generated test cases from symbolic execution trajectories
Generated by KIMVIEware Phase 4 Executor
"""
import pytest
import requests
import warnings

BASE_URL = "http://localhost:8000"


def test_js_3():
    """Test case for trajectory js_3 (register)"""
    # Test user registration
    payload = {
        "username": "testuser0",
        "password": "Test12340",
        "email": "test0@example.com",
        "full_name": "Test User 0"
    }
    response = requests.post(f"{BASE_URL}/auth/register", json=payload)
    # Flexible validation: accept success (201), user error (400), 
    # conflict (409), or validation error (422)
    assert response.status_code in [200, 201, 400, 409, 422]

def test_js_1():
    """Test case for trajectory js_1 (login)"""
    # Test login
    payload = {
        "username": "admin",
        "password": "Admin123!"
    }
    response = requests.post(f"{BASE_URL}/auth/login", json=payload)
    # 200: success, 401: unauthorized, 403: forbidden (disabled account)
    assert response.status_code in [200, 401, 403, 422]
