/**
 * Auto-generated test cases from symbolic execution trajectories
 * Generated by KIMVIEware Phase 4 Executor
 */

const BASE_URL = "http://localhost:8000";

describe("Auto-generated API Tests", () => {

    test("Test case for trajectory js_3 (register)", async () => {
        // Test user registration
        const payload = {
            username: "testuser0",
            password: "Test12340",
            email: "test0@example.com",
            full_name: "Test User 0"
        };
        const response = await fetch(`${BASE_URL}/auth/register`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload)
        });
        expect([200, 201, 400, 409, 422]).toContain(response.status);
    });

    test("Test case for trajectory js_1 (login)", async () => {
        // Test login
        const payload = {
            username: "admin",
            password: "Admin123!"
        };
        const response = await fetch(`${BASE_URL}/auth/login`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload)
        });
        expect([200, 401, 403, 422]).toContain(response.status);
    });
});
