# Generated by Django 5.2.11 on 2026-02-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('BELGIQUE', 'Économie et Société – Belgique'), ('CONGO', 'Économie et Société – République du Congo'), ('FINANCE', 'Finance et Gestion')], default='BELGIQUE', max_length=50),
        ),
    ]
